### ISSUE TITLE
decaf程序没有任何class时编译器会崩溃

### ISSUE THREAD

**Issue by TRCYX** [decaf-lang/decaf-in-scala#3]
在 `DecafParser.g4` 中，`topLevel` 的产生式是 `classDef*`，而 `Parser.scala` 中 `visitTopLevel` 时将 `TopLevel` 的位置设置为 `classes.head` 的位置，产生 `NoSuchElementException`。

**Comment by paulzfm** [comment]
语言规范：

```
topLevel    ::= classDef+
```

因此 `DecafParser.g4` 的实现不对。
